apiVersion: argoproj.io/v1alpha
kind: Workflow
metadata:
    generateName: solid-deosil-ci-cd-
    namespace: argo
spec:
    serviceAccountName: workflow-executor
    entrypoint: main-pipeline
    volumes:
        - name: workspace
          hostPath:
              path: /home/ky/dev/boxes/minikube-storage
        - name: docker-sock
          hostPath:
              path: /var/run/docker.sock

    arguments:
        parameters:
            - name: image-tag
              value: "latest"
            - name: git-repo
              value: "https://github.com/ZweitDev/solid-deosil.git"
            - name: git-branch
              value: "main"

    templates:
        - name: main-pipeline
          steps:
              - - name: checkout-code
                  template: git-checkout
              - - name: verify-files
                  template: verify-files
              - - name: build-image
                  template: build-docker-image
                  arguments:
                      parameters:
                          - name: image-tag
                            value: "{{workflow.parameters.image-tag}}"
              - - name: push-image
                  template: push-docker-image
                  arguments:
                      parameters:
                          - name: image-tag
                            value: "{{workflow.parameters.image-tag}}"

        - name: git-checkout
          container:
              image: alpine/git
              command: [sh, -c]
              args: [
                      "git clone {{workflow.parameters.git-repo}} -b {{workflow.parameters.git-branch}} /src
                      && ls -la /src",
                  ]
              volumeMounts:
                  - name: workspace
                    mountPath: /src

        - name: verify-files
          container:
              image: alpine
              command: [sh, -c]
              args: ["ls -la /src"]
              volumeMounts:
                  - name: workspace
                    mountPath: /src

        - name: build-docker-image
          inputs:
              parameters:
                  - name: image-tag
          container:
              image: docker:20.10
              workingDir: /src
              command: [sh, -c]
              args:
                  [
                      "ls -la && docker build -t registry.minikube/solid-deosil:{{inputs.parameters.image-tag}} .",
                  ]
              volumeMounts:
                  - name: workspace
                    mountPath: /src
                  - name: docker-sock
                    mountPath: /var/run/docker.sock

        - name: push-docker-image
          inputs:
              parameters:
                  - name: image-tag
          container:
              image: docker:20.10
              command: [sh, -c]
              args:
                  [
                      "docker push registry.minikube/solid-deosil:{{inputs.parameters.image-tag}}",
                  ]
              volumeMounts:
                  - name: docker-sock
                    mountPath: /var/run/docker.sock

        - name: trigger-argocd-sync
          container:
              image: curlimages/curl
              command: [sh, -c]
              args:
                  [
                      'curl -X POST -H "Authorization: Bearer $ARGO_TOKEN" https://argocd.your-domain.com/api/v1/applications/vite-app/sync',
                  ]
              env:
                  - name: ARGO_TOKEN
                    valueFrom:
                        secretKeyRef:
                            name: argocd-credentials
                            key: token
